#!perl
use v5.36;
use FindBin;
use Cwd qw(realpath);

my $config_name = "poc";

my @passthru;

while (@ARGV && $ARGV[0] =~ /^-/) {
  my $opt = shift;
  if ($opt eq "-n") {
    @ARGV or die "$0: no argument for -n";
    $config_name = shift;
    push @passthru, "-n", $config_name;
  }
  elsif ($opt =~ /^-[ADU]\w+/) {
    push @passthru, $opt;
  }
  else {
    die "Unknown argument '$opt'\n";
  }
}

$ENV{PKG_CONFIG_PATH} = "$ENV{HOME}/local/libperf/lib64/pkgconfig/";

my $git = realpath("$FindBin::Bin/../../perf-perl-github");
my $install = realpath("$FindBin::Bin/../../perl-perf-built");
my $reports = realpath("$FindBin::Bin/../../perl-perf-reports");

print <<"EOS";
git: $git
install: $install
reports: $reports
config_name: $config_name
passthru: @passthru
EOS

for my $sha (@ARGV) {
  print "$sha\n";
  my $report = "$reports/$sha-$config_name.json";
  my $log = "$reports/$sha-$config_name.log";
  print "    report: $report\n";
  print "    log   : $log\n";

  if (-f $report) {
    print " Report exists, skipping build\n";
  }
  else {
    system "perl scripts/perl-perf-poc $git $sha $install $report >$log 2>&1"
      and next;
  }
  system "lwp-request -m PUT -c application/json https://perldev.develop-help.com/api/perf/vdev/report/$sha/$config_name <$report";
}

